baseURL = "https://drax-x9.netlify.app/"
languageCode = "sw"
defaultContentLanguage = "sw"
title = "DRAX X9"
theme = "gohugo-theme-ananke"

[languages]
  [languages.sw]
    languageName = "Kiswahili"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

[params]
  description = "DRAX X9 - Kituo chako kwa taarifa za Hacking na Teknolojia."
  profile_picture = "https://i.ibb.co/nqw7GXVj/Drax-X9-Profile.png"
  text_color = "text-lime-300"
  bg_color = "bg-black"
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Info"
    url = "/info"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

[contact]
  phone = "+255614615384"
  whatsapp = "https://wa.me/255614615384"
  telegram = "https://t.me/DraxX9"

